/* Walks the five demo story threads through the store and prints the figures after each step. */
import * as st from "../src/jodz/store";
import * as d from "../src/jodz/derive";
import { briefing, answerFor } from "../src/jodz/home";
const s = () => st.getState();
const line = (t: string) => console.log("\n## " + t);
const cash = (o = {}) => d.cashOutlook(s(), o).horizons.map((h) => h.closing).join(" / ");
line("start"); console.log(briefing(s()).map((b) => b.text).join("\n"));
line("B: propose partial dispatch W1041, approve");
st.proposePartialDispatch("JOD-W1041");
const ap = s().approvals.find((a) => a.kind === "Partial dispatch")!;
st.decideApproval(ap.id, true);
let r = d.orderRow(s(), s().orders.find((o) => o.id === "JOD-W1041")!);
console.log(r.fulfilment, r.payment, "open", r.openValue, "short", r.short, "invoices", r.invoices.map((i) => i.id + ":" + i.net));
let ss = d.salesSummary(s()); console.log("net", ss.net, "wholesale", ss.wholesale, "open book", d.openOrderBook(s()).value, "cash", cash());
line("A/B: receive PO-0187, reserve remaining for W1041");
st.receivePO("PO-0187"); st.reserveStock("JOD-W1041");
r = d.orderRow(s(), s().orders.find((o) => o.id === "JOD-W1041")!);
console.log("W1041", r.allocation, r.unallocated, "AN-S avail", d.variantRows(s()).find((v) => v.sku === "JZ-AN-S")!.available, "MB-M avail", st.availableFor(s(), "JZ-MB-M"));
st.dispatchOrder("JOD-W1041"); r = d.orderRow(s(), s().orders.find((o) => o.id === "JOD-W1041")!);
console.log("W1041", r.o.stage, r.fulfilment, "invoiced", r.invoices.reduce((a, i) => a + i.net, 0), "open book", d.openOrderBook(s()).value);
line("C: approve reminder, record payment");
st.approveReminder("JOD-INV2031"); console.log("bank before", d.bankCash(s()), "cash", cash());
st.recordPayment("JOD-INV2031"); console.log("bank after", d.bankCash(s()), "cash", cash(), "AR", d.receivables(s()).total);
st.recordPayment("JOD-INV2031"); console.log("double record bank", d.bankCash(s()));
line("D: CFP-L return + clearance");
st.decideReturn("RET-316"); st.setClearanceReview(true); console.log("CFP-L avail", st.availableFor(s(), "JZ-CF-L"));
st.decideReturn("RET-314"); console.log("AN-S onHand", s().variants.find((v) => v.sku === "JZ-AN-S")!.onHand, "AN-M onHand", s().variants.find((v) => v.sku === "JZ-AN-M")!.onHand, "net", d.salesSummary(s()).net);
line("E: approve PO-D193");
console.log("preview", cash({ includeDraft: true }));
st.decideApproval("AP-31", true); console.log("after approve", cash(), "bank", d.bankCash(s()), "incoming AN-S", d.variantRows(s()).find((v) => v.sku === "JZ-AN-S")!.incoming);
st.decideApproval("AP-31", true); console.log("double approve", cash());
line("end"); console.log(briefing(s()).map((b) => b.text).join("\n"));
console.log(answerFor("Can we afford the proposed stock purchase?").text);
console.log("activity", s().activity.length, "tasks done", s().tasks.filter((t) => t.status === "Done").map((t) => t.id));
